- name: boostnote - get latest
  uri:
    url: https://github.com/BoostIO/boost-releases/releases/latest
  register: result

- name: boostnote - extracting
  set_fact:
    version: "{{ result.url | regex_replace('^.*v(\\d\\.\\d\\d\\.\\d\\d)$', '\\1')}}"

- name: boostnote - check if deb is already downloaded
  stat:
    path: "{{ thirdparty }}/boostnote_{{ version }}_amd64.deb"
  register: boostnote_deb

- name: boostnote - downloading deb package
  get_url:
    url: "https://github.com/BoostIO/boost-releases/releases/download/v{{ version }}/boostnote_{{ version }}_amd64.deb"
    dest: "{{ thirdparty }}"
  when: boostnote_deb.stat.exists == False

- name: boostnote - install deb package
  apt:
    deb: "{{ thirdparty }}/boostnote_{{ version }}_amd64.deb"
  become: true
  tags:
    - install
